totvs/winthor-smart-hub-layouts

- pdvsync/2-pcintegracaorotaservico/PDVSYNC - ENVIAR ICMS.json
Correção do layout PDVSYNC - Enviar ICMS
> DWSHWTNG-218-atualizacaoLayoust-main

- pdvsync/2-pcintegracaorotaservico/WTA - CONSULTA RCA.json
- pdvsync/3-pcintegracaovariaveis/WTA - Consulta RCA.json
- pdvsync/9-pcintegracaofluxoexecucao/FLUXO-25-PDVSYNC - Criar variavel temporária-classe-CriaVariavelTemporaria.json
- pdvsync/9-pcintegracaofluxoexecucao/FLUXO-25-PDVSYNC - Encerrar variavel temporaria-classe-FinalizaVariavelTemporaria.json
- pdvsync/9-pcintegracaofluxoexecucao/FLUXO-25-PDVSYNC - LoginPDVSync-classe-AutenticadorRefreshTokenApi.json
- pdvsync/9-pcintegracaofluxoexecucao/FLUXO-25-PDVSYNC - Salvar Usuario Operador-classe-EnvioIntegracaoStatusRecebidoLote.json
- pdvsync/9-pcintegracaofluxoexecucao/FLUXO-25-PDVSYNC -LoginWTA-classe-AutenticadorRefreshTokenApi.json
- pdvsync/9-pcintegracaofluxoexecucao/FLUXO-25-WTA - Consulta RCA-classe-BuscaRotaServicoNaoPaginada.json
Fluxo 25, Rota WTA - CONSULTA RCA e Variaveis.
> Criação de fluxo e Rota.

- CODEOWNERS
> Dwshwtng 315 correcao agendamento fluxo

- README.md
- Adição da documetação de como clonar e fazer o checkout para o brach;
-  Documentação de como criar um arquivo de rotas;
-  Documentação de como criar um arquivo de variaveis;
-  Documentação de como criar um arquivo de fluxo.
> Dwshwtng 132 documentacao readme develop

- pdvsync/fluxos/FLUXO-26-PDVSYNC - Consultar status lote-classe-BuscaRotaServicoNaoPaginada.json
- pdvsync/fluxos/FLUXO-26-WTA - Atualizar status lote PDV-classe-EnvioIntegracaoStatusRecebido.json
- pdvsync/fluxos/FLUXO-26-WTA - Buscar lote PDV-classe-BuscaRotaServicoPaginada.json
- pdvsync/fluxos/FLUXO-26-WTA - Finalizar integra status lote PDV-classe-EnvioIntegracaoStatusRecebido.json
- pdvsync/fluxos/FLUXO-26-WTA - LoginWTA-classe-AutenticadorRefreshTokenApi.json
- pdvsync/rotas/PDVSYNC - CONSULTAR STATUS LOTE.json
- pdvsync/rotas/WTA - ATUALIZAR STATUS LOTE PDV.json
- pdvsync/rotas/WTA - BUSCAR LOTE PDV.json
- pdvsync/rotas/WTA - FINALIZAR INTEGRA STATUS LOTE PDV.json
- pdvsync/variaveis/PDVSYNC - Consultar status lote-{{BASE_URL_STATUS_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Consultar status lote-{{ID_INQUILINO}}.json
- pdvsync/variaveis/PDVSYNC - Consultar status lote-{{NUMERO_LOTE}}.json
- pdvsync/variaveis/WTA - Atualizar status lote PDV-{{CLIENT_JSON}}.json
- pdvsync/variaveis/WTA - Finalizar integra status lote PDV-{{CLIENT_JSON}}.json
Ddintegra 11622 main rota atualizar status lote
> Ddintegra 11622 main rota atualizar status lote

- pdvsync/erroRequisicao/ERRO_REQUISICAO_CRIAR_FINALIZAR_LOTE.json
- pdvsync/fluxos/FLUXO-10-PDVSYNC - Enviar Estoque-classe-EnvioIntegracaoStatusRecebidoLote.json
- pdvsync/fluxos/FLUXO-19-WTA - ENVIAR PEDIDO RECEBIDO-classe-EnvioIntegracaoStatusRecebido.json
- pdvsync/fluxos/FLUXO-20-WTA - ENVIAR PEDIDO CANCELADO-classe-EnvioIntegracaoStatusRecebido.json
- pdvsync/rotas/PDVSYNC - CRIAR VARIAVEL TEMPORARIA.json
- pdvsync/rotas/PDVSYNC - ENCERRAR VARIAVEL TEMPORARIA.json
- pdvsync/rotas/WTA - ENVIAR PEDIDO CANCELADO.json
- pdvsync/rotas/WTA - ENVIAR PEDIDO RECEBIDO.json
- pdvsync/variaveis/PDVSYNC - Criar variavel temporaria-{{BASE_URL_ABRIR_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Criar variavel temporaria-{{INQUILINO}}.json
- pdvsync/variaveis/PDVSYNC - Criar variavel temporaria-{{TIPO_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Encerrar variavel temporaria-{{BASE_URL_FECHAR_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Encerrar variavel temporaria-{{INQUILINO}}.json
- pdvsync/variaveis/WTA - ENVIAR PEDIDO CANCELADO-{{CLIENT_JSON}}.json
- pdvsync/variaveis/WTA - ENVIAR PEDIDO RECEBIDO-{{CLIENT_JSON}}.json
Adição dos dados da tabeça PCINTEGRACAOERROREQUISICAO
> DWSHWTNG-360-adicaoErroRequisicao

- pdvsync/rotas/WTA - BUSCAR CLIENTES.json
- pdvsync/rotas/WTA - BUSCAR ESTOQUE.json
- pdvsync/rotas/WTA - BUSCAR FILIAIS COMPARTILHAMENTO.json
- pdvsync/rotas/WTA - BUSCAR FILIAIS LOJAS.json
- pdvsync/rotas/WTA - BUSCAR ICMS.json
- pdvsync/rotas/WTA - BUSCAR IMPOSTO NCM PDV.json
- pdvsync/rotas/WTA - BUSCAR OPERADORA PDV.json
- pdvsync/rotas/WTA - BUSCAR PLANOS DE PGTO.json
- pdvsync/rotas/WTA - BUSCAR PRODUTO PDV.json
- pdvsync/rotas/WTA - BUSCAR STATUS PEDIDO.json
- pdvsync/rotas/WTA - BUSCAR USUARIO OPERADOR.json
Ajuste nos adapter para gravar corretamente nas colunas "tipoIdInterno" = PCINTEGRACAOCORE.TIPODOCUMENTO "idInterno" = PCINTEGRACAOCORE.IDINTERNO
> DDINTEGRA-11710

- pdvsync/parametros/AMBIENTE_HOMOLOGACAO.json
- pdvsync/parametros/AMBIENTE_PRODUCAO.json
Ajustes para igualar o nome da rota, contida nos arquivos de parâmetros, com o nome da rota servico
> DWSHWTNG-375-nomeRotaNasUrls

- pdvsync/variaveis/PDVSYNC - Buscar Pedidos CANCELADA-{{ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Buscar movimentacoes caixa-{{ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Buscar vendas-{{ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - ENVIAR PIS COFINS-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar ICMS-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar Preco Produto-{{FILIAL_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar compartilhamentos-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar formas de pgto-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar lojas-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar planos de pgto-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - RAC LoginPDVSync-{{CLIENT_ID}}.json
- pdvsync/variaveis/PDVSYNC - RAC LoginPDVSync-{{CLIENT_SECRET}}.json
- pdvsync/variaveis/PDVSYNC - RAC LoginPDVSync-{{PASSWORD}}.json
- pdvsync/variaveis/PDVSYNC - RAC LoginPDVSync-{{USERNAME}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Clientes-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Imposto NCM-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Operadora-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Produto-{{FILIAL_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Usuario Operador-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/WTA - Buscar Operadora PDV-{{FILIAL}}.json
- pdvsync/variaveis/WTA - Buscar Perfil PADRAO-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/WTA - Buscar status pedido-{{FILIAL}}.json
- pdvsync/variaveis/WTA - Consulta RCA-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/WTA - Dados pagamento-{{MASTER_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/WTA - LoginWTA-{{LOGIN}}.json
- pdvsync/variaveis/WTA - LoginWTA-{{SENHA}}.json
- pdvsync/variaveis/WTA - PDVSYNC Compartilhamento Master-{{MASTER_ID_PROPRIETARIO}}.json
- ajuste para gravar algumas variáveis com o valor padrão
> DWSHWTNG-415-correcaoErroVariaveisPadrao

- pdvsync/rotas/WTA - BUSCAR CLIENTES.json
API Já alterada para enviar os novos campos.
> inclusão de dois campos novos no adapter (Sexo e DataNascimento).

- pdvsync/rotas/PDVSYNC - BUSCAR VENDAS.json
DDINTEGRA-11925 - Adapter Venda SAT
> DDINTEGRA-11925 - Adapter Venda SAT

- pdvsync/rotas/WTA - BUSCAR PRODUTO PDV.json
Ajuste nos campos de item do KIT para atender um pedido de ajuste do PDVSync
> DDINTEGRA-12150

- pdvsync/rotas/WTA - CONSULTA RCA.json
- pdvsync/variaveis/WTA - Consulta RCA-{{DATECAD}}.json
- pdvsync/variaveis/WTA - Consulta RCA-{{DATEEND}}.json
- pdvsync/variaveis/WTA - Consulta RCA-{{DATEINITIAL}}.json
ROTA RCA - Transformação adicionando campos
ROTA RCA - Comunicação: adicionando variaveis de data
*API ja esta modificada para receber os novos parametros"
Testado local via WSH.
> Ajuste Rotas e adicionando Variaveis para a ROTA RCA.

- pdvsync/fluxos/FLUXO-24-Atualizar Status Lote Retaguarda-3-PDVSYNC - Consultar status lote.json
- pdvsync/fluxos/FLUXO-24-Atualizar Status Lote Retaguarda-3-PDVSYNC - LoginPDVSync.json
- pdvsync/fluxos/FLUXO-24-Atualizar Status Lote Retaguarda-4-PDVSYNC - Consultar status lote.json
- pdvsync/fluxos/FLUXO-24-Atualizar Status Lote Retaguarda-5-WTA - Atualizar status lote PDV.json
- pdvsync/fluxos/FLUXO-24-Atualizar Status Lote Retaguarda-6-WTA - Finalizar integra status lote PDV.json
- pdvsync/rotas/WTA - BUSCAR LOTE PDV.json
- pdvsync/variaveis/PDVSYNC - Consultar status lote-{{NUMERO_LOTE}}.json
Ajustes para possibilitar chamar duas buas sequenciais com substituição de variáveis
> DWSHWTNG-619-refatorarMetodoTratarVariaveis

- pdvsync/rotas/WTA - BUSCAR PRECO PRODUTO.json
Fiz um ajuste pois foi removido equivocadamente do layout da rota de busca de preço a geração das informações de "tipoIdInterno" = PCINTEGRACAOCORE.TIPODOCUMENTO e "idInterno" = PCINTEGRACAOCORE.IDINTERNO
> DDWMISSI-196

- pdvsync/rotas/WTA - BUSCAR CLIENTES.json
Inserido novo campo IdProfissionalRetaguarda no JSON de envio para o PDVSync
> DDWMISSI-651

- pdvsync/parametros/AMBIENTE_HOMOLOGACAO.json
- pdvsync/parametros/AMBIENTE_PRODUCAO.json
- pdvsync/variaveis/PDVSYNC - Atualiza Status-{{URL_ATUALIZAR_STATUS_PEDIDO}}.json
- pdvsync/variaveis/PDVSYNC - Atualizar status caixa-{{URL_ATUALIZAR_STATUS_CAIXA}}.json
- pdvsync/variaveis/PDVSYNC - Atualizar status venda-{{URL_ATUALIZAR_STATUS_VENDA}}.json
- pdvsync/variaveis/PDVSYNC - Buscar Pedidos CANCELADA-{{URL_CONSULTA_VENDAS}}.json
- pdvsync/variaveis/PDVSYNC - Buscar Pedidos RECEBIDO-{{URL_CONSULTA_VENDAS}}.json
- pdvsync/variaveis/PDVSYNC - Buscar movimentacoes caixa-{{URL_CONSULTA_MOVIMENTACAO_CAIXA}}.json
- pdvsync/variaveis/PDVSYNC - Buscar vendas-{{URL_CONSULTA_VENDAS}}.json
- pdvsync/variaveis/PDVSYNC - Consultar lote-{{URL_CONSULTAR_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Criar variavel temporaria-{{BASE_URL_ABRIR_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Dados pagamento-{{URL_ENVIAR_DADOS_PAGAMENTO}}.json
- pdvsync/variaveis/PDVSYNC - ENVIAR PIS COFINS-{{URL_ENVIAR_PIS_COFINS}}.json
- pdvsync/variaveis/PDVSYNC - Encerrar variavel temporaria-{{BASE_URL_FECHAR_LOTE}}.json
- pdvsync/variaveis/PDVSYNC - Envia status pedido-{{URL_ENVIAR_STATUS_PREVENDA}}.json
- pdvsync/variaveis/PDVSYNC - Enviar Estoque-{{URL_ENVIAR_ESTOQUE_DISPONIVEL}}.json
- pdvsync/variaveis/PDVSYNC - Enviar ICMS-{{URL_ENVIAR_ICMS}}.json
- pdvsync/variaveis/PDVSYNC - Enviar Preco Produto-{{URL_ENVIAR_PRECO_PRODUTOS}}.json
- pdvsync/variaveis/PDVSYNC - Enviar compartilhamentos-{{URL_ENVIAR_COMPARTILHAMENTO}}.json
- pdvsync/variaveis/PDVSYNC - Enviar formas de pgto-{{URL_ENVIAR_FORMAS_PGMT}}.json
- pdvsync/variaveis/PDVSYNC - Enviar lojas-{{URL_ENVIAR_LOJAS}}.json
- pdvsync/variaveis/PDVSYNC - Enviar planos de pgto-{{URL_ENVIAR_CONDICAO_PGMT}}.json
- pdvsync/variaveis/PDVSYNC - Registrar IP-{{URL_REGISTRAR_IP}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Clientes-{{URL_ENVIAR_CLIENTE}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Imposto NCM-{{URL_ENVIAR_NCM}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Operadora-{{URL_ENVIAR_OPERADORA}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Perfil-{{URL_ENVIAR_PERFIL}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Produto-{{URL_ENVIAR_PRODUTO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Usuario Operador-{{URL_ENVIAR_USUARIO_OPERADOR}}.json
Ajustei as URL dos campos de variaveis para que aponte sempre para o ambiente PRODUÇÃO e os arquivos de Homologação e Produção para versão V2.
> DDWMISSI-835

- pdvsync/fluxos/FLUXO-27-Regiao-1-WTA - LoginWTA.json
- pdvsync/fluxos/FLUXO-27-Regiao-2-WTA - Buscar Regiao PDV.json
- pdvsync/fluxos/FLUXO-27-Regiao-3-PDVSYNC - LoginPDVSync.json
- pdvsync/fluxos/FLUXO-27-Regiao-4-PDVSYNC - Criar variavel temporaria.json
- pdvsync/fluxos/FLUXO-27-Regiao-5-PDVSYNC - Salvar Regiao.json
- pdvsync/fluxos/FLUXO-27-Regiao-6-PDVSYNC - Encerrar variavel temporaria.json
- pdvsync/parametros/AMBIENTE_HOMOLOGACAO.json
- pdvsync/parametros/AMBIENTE_PRODUCAO.json
- pdvsync/rotas/PDVSYNC - SALVAR REGIAO.json
- pdvsync/rotas/WTA - BUSCAR REGIAO PDV.json
- pdvsync/variaveis/PDVSYNC - Salvar Regiao-{{CLIENT_JSON}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Regiao-{{FILIAL_ID_PROPRIETARIO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Regiao-{{ID_INQUILINO}}.json
- pdvsync/variaveis/PDVSYNC - Salvar Regiao-{{URL_ENVIAR_REGIAO}}.json
- pdvsync/variaveis/WTA - Buscar Regiao PDV-{{FILIAL}}.json
- pdvsync/variaveis/WTA - Buscar Regiao PDV-{{LAST_CHANGE}}.json
Criado um novo fluxo 27 de envio de região para o PDVSync.
> DDWMISSI-722

- coleta-entrega/dadosEmpresa/COLETA-ENTREGA.json
- coleta-entrega/dadosEmpresa/WTA-COLETA-ENTREGA.json
- coleta-entrega/rotas/COLENT - BUSCA CLIENTE DEPARA.json
- coleta-entrega/rotas/COLENT - BUSCAR COLETA.json
- coleta-entrega/rotas/COLENT - BUSCAR ENTREGA.json
- coleta-entrega/rotas/COLENT - BUSCAR VIAGEM.json
- coleta-entrega/variaveis/COLENT - RAC LOGIN -{{CLIENT_ID}}.json
- coleta-entrega/variaveis/COLENT - RAC LOGIN -{{CLIENT_SECRET}}.json
- coleta-entrega/variaveis/COLENT - RAC LOGIN -{{SENHA_RAC}}.json
- coleta-entrega/variaveis/COLENT - RAC LOGIN -{{URL_RAC_COLETA_ENTREGA}}.json
- coleta-entrega/variaveis/COLENT - RAC LOGIN -{{USUARIO_RAC}}.json
- coleta-entrega/variaveis/WTA-COLENT - LOGIN -{{LOGIN}}.json
- coleta-entrega/variaveis/WTA-COLENT - LOGIN -{{SENHA}}.json
Removido page e page size de rotas nao paginadas
> ddestoque 19522 - Ajuste rotas sem paginacao e variaveis com palavra reservada

- pdvsync/rotas/WTA - BUSCAR PRECO FIXO.json
- Correção para o campo idproprietário
> DDWMISSI-939-adapter-preco-fixo

- pdvsync/rotas/WTA - BUSCAR PRODUTO PDV.json
Ajuste no layout WTA - Buscar Produto PDV, com a nova descrição do campo.
> DDWMISSI-1023

- pdvsync/agendamentoFluxos/pdvsyncConsultarStatusLote.json
- pdvsync/agendamentos/PDVSYNC - CONSULTAR STATUS LOTE.json
- pdvsync/rotas/PDVSYNC - CONSULTAR STATUS LOTE.json
- pdvsync/variaveis/PDVSYNC - Consultar status lote-{{FILIAL}}.json
- Alteração da consulta de PDVSYNC - CONSULTAR STATUS LOTE adicionando o IDRetaguarda que é a filial da Loja;
- Criação do agendamento do PDVSYNC - CONSULTAR STATUS LOTE
> DDWMISSI-556_PDVSYNC - CONSULTAR STATUS LOTE

- pdvsync/rotas/WTA - BUSCAR USUARIO OPERADOR.json
- Adicionado o campo de Senha para o fluxo Usuario Operador
> DDWMISSI-1124-DEVELOP

- pdvsync/variaveis/WTA - Buscar venda integracao-{{DATA_HORA-FIM}}.json
- pdvsync/variaveis/WTA - Buscar venda monitor-{{DATA_HORA-FIM}}.json
- Correção do formato da variavael de hora fim do fluxo de Buscar venda monitor e Buscar venda integracao
> DDWMISSI-1203-DEVELOP

- pdvsync/rotas/PDVSYNC - BUSCAR VENDAS.json
- Alteracao do nome do campo de IdRetaguardaProfissional para ficar no formato padrao
> DDWMISSI-1210-RELEASE

- pdvsync/rotas/PDVSYNC - BUSCAR VENDAS.json
- Alteracao do nome do campo de IdRetaguardaProfissional para ficar no formato padrao
> DDWMISSI-1210-DEVELOP

- .github/workflows/criar-tag-release.yml
git config --global user.email "deyvid.costa@totvs.com.br"
> git config --global user.name "deyvidtotvs"

- pdvsync/rotas/WTA - CONSULTA RCA.json
Ajuste no layout de consulta RCA
> DDWMISSI-1294

- pdvsync/rotas/WTA - BUSCAR PRECO FIXO.json
- Adicionado o campo idRetaguardaProdutoEmbalagem na rota do preco fixo
> DDWMISSI-1300-DEVELOP

- pdvsync/rotas/PDVSYNC - SALVAR CLIENTES.json
- pdvsync/rotas/PDVSYNC - SALVAR RAMO ATIVIDADE.json
Ajuste no layout de salvar cliente e salvar ramo atividade
> DDWMISSI-1304

- pdvsync/rotas/WTA - BUSCAR CLIENTES.json
- Ajustado o campo idRetaguardaProfissional
> DDWMISSI-1325-MASTER

- pdvsync/rotas/WTA - BUSCAR TIPOS COBRANCAS.json
> DDWMISSI-1228 Alteracao na rota Buscar Tipos Cobrancas

- pdvsync/parametros/AMBIENTE_HOMOLOGACAO.json
- pdvsync/parametros/AMBIENTE_PRODUCAO.json
Alterado para /v3/dadosdinamicos/down/18/2
> DDWMISSI-1454 - Alterações do parâmetro URL_ENVIAR_FORMAS_PGMT

- pdvsync/variaveis/WTA - Consulta RCA-{{BRANCHID}}.json
- Adicionado o valor dinamico ADICIONAR_FILIAL
> DDWMISSI-1748-MASTER

- pdvsync/variaveis/WTA - Consulta RCA-{{BRANCHID}}.json
- Adicionado o valor dinamico ADICIONAR_FILIAL
> DDWMISSI-1748-DEVELOP

- pdvsync/parametros/AMBIENTE_PRODUCAO.json
No momento que foi feito a virada de versão na Varejão foi identificado que algumas URL estava incorretas e e fiz a correção aqui nessa issue.
Lista de URL ajustada:
URL_ENVIAR_GRUPO_CAMPANHA_CLIENTE
URL_ENVIAR_PROFISSIONAL
URL_ENVIAR_REGIAO
URL_ENVIAR_RAMO_ATIVIDADE
Baseado em https://tdn.totvs.com/pages/viewpage.action?pageId=831821611
> DDWMISSI-2140

- tre/fluxos/FLUXO-03-TRE-ENVIAR_NOTAS_FISCAIS-1-WTA-REST AUTH.json
- tre/fluxos/FLUXO-03-TRE-ENVIAR_NOTAS_FISCAIS-2-WTA-BUSCAR_NOTAS_FISCAIS_REST.json
- tre/fluxos/FLUXO-03-TRE-ENVIAR_NOTAS_FISCAIS-3-TRE-SOAP AUTH.json
- tre/fluxos/FLUXO-03-TRE-ENVIAR_NOTAS_FISCAIS-4-TRE-ENVIAR_NOTAS_FISCAIS.json
- tre/rotas/TRE-ENVIAR_NOTAS_FISCAIS.json
- tre/rotas/WTA-BUSCAR_NOTAS_FISCAIS_REST.json
- tre/rotas/WTA-BUSCAR_PRODUTOS_REST.json
- tre/variaveis/TRE-ENVIAR_NOTAS_FISCAIS -{{CLIENT_JSON}}.json
https://jiraproducao.totvs.com.br/browse/DDESTOQUE-20384
> Adapter de Nota Fiscal

- tre/fluxos/FLUXO-05-TRE-LIBERAR_VIAGEM-1-TRE-SOAP AUTH.json
- tre/fluxos/FLUXO-05-TRE-LIBERAR_VIAGEM-2-TRE-BUSCAR_VIAGENS_LIBERADAS.json
- tre/fluxos/FLUXO-05-TRE-LIBERAR_VIAGEM-3-WTA-REST AUTH.json
- tre/fluxos/FLUXO-05-TRE-LIBERAR_VIAGEM-4-WTA-PROCESSAR_CARGA.json
- tre/fluxos/FLUXO-06-TRE-CANCELAR_VIAGEM-1-TRE-SOAP AUTH.json
- tre/fluxos/FLUXO-06-TRE-CANCELAR_VIAGEM-2-TRE-BUSCAR_VIAGENS_CANCELADAS.json
- tre/fluxos/FLUXO-06-TRE-CANCELAR_VIAGEM-3-WTA-REST AUTH.json
- tre/fluxos/FLUXO-06-TRE-CANCELAR_VIAGEM-4-WTA-CANCELAR_CARGA.json
- tre/rotas/TRE-BUSCAR_VIAGENS_CANCELADAS.json
- tre/rotas/TRE-BUSCAR_VIAGENS_LIBERADAS.json
- tre/rotas/WTA-BUSCAR_LOCALIDADES_REST.json
- tre/rotas/WTA-BUSCAR_NOTAS_FISCAIS_REST.json
- tre/rotas/WTA-BUSCAR_PEDIDOS_REST.json
- tre/rotas/WTA-BUSCAR_PRODUTOS_REST.json
- tre/variaveis/TRE-BUSCAR_VIAGENS_CANCELADAS -{{REGION_SOURCE_ID}}.json
- tre/variaveis/TRE-BUSCAR_VIAGENS_LIBERADAS -{{REGION_SOURCE_ID}}.json
- tre/variaveis/WTA-CANCELAR_CARGA -{{CLIENT_JSON}}.json
- tre/variaveis/WTA-PROCESSAR_CARGA -{{CLIENT_JSON}}.json
https://jiraproducao.totvs.com.br/browse/DDESTOQUE-20380
https://jiraproducao.totvs.com.br/browse/DDESTOQUE-20381
> Adapter de sincronização e cancelar viagem

- tre/fluxos/FLUXO-11-TRE-ENVIAR-RETORNOS-CANCELAMENTO-1-WTA-REST AUTH.json
- tre/fluxos/FLUXO-11-TRE-ENVIAR-RETORNOS-CANCELAMENTO-2-WTA-BUSCAR_MSG_RETORNO_CANCEL_REST.json
- tre/fluxos/FLUXO-11-TRE-ENVIAR-RETORNOS-CANCELAMENTO-3-TRE-SOAP AUTH.json
- tre/fluxos/FLUXO-11-TRE-ENVIAR-RETORNOS-CANCELAMENTO-4-TRE-ENVIAR_MSG_RETORNO_CANCEL.json
- tre/fluxos/FLUXO-12-TRE-ENVIAR-RETORNOS-LIBERACAO-VIAGEM-1-WTA-REST AUTH.json
- tre/fluxos/FLUXO-12-TRE-ENVIAR-RETORNOS-LIBERACAO-VIAGEM-2-WTA-BUSCAR_MSG_RETORNO_LIB_VIAG_REST.json
- tre/fluxos/FLUXO-12-TRE-ENVIAR-RETORNOS-LIBERACAO-VIAGEM-3-TRE-SOAP AUTH.json
- tre/fluxos/FLUXO-12-TRE-ENVIAR-RETORNOS-LIBERACAO-VIAGEM-4-TRE-ENVIAR_MSG_RETORNO_LIB_VIAG.json
- tre/fluxos/FLUXO-13-TRE-ENVIAR-RETORNOS-REPROGRAMACAO-1-WTA-REST AUTH.json
- tre/fluxos/FLUXO-13-TRE-ENVIAR-RETORNOS-REPROGRAMACAO-2-WTA-BUSCAR_MSG_RETORNO_REPROG_REST.json
- tre/fluxos/FLUXO-13-TRE-ENVIAR-RETORNOS-REPROGRAMACAO-3-TRE-SOAP AUTH.json
- tre/fluxos/FLUXO-13-TRE-ENVIAR-RETORNOS-REPROGRAMACAO-4-TRE-ENVIAR_MSG_RETORNO_REPROG.json
- tre/rotas/TRE-ENVIAR_MSG_RETORNO_CANCEL.json
- tre/rotas/TRE-ENVIAR_MSG_RETORNO_LIB_VIAG.json
- tre/rotas/TRE-ENVIAR_MSG_RETORNO_REPROG.json
- tre/rotas/WTA-BUSCAR_MSG_RETORNO_CANCEL_REST.json
- tre/rotas/WTA-BUSCAR_MSG_RETORNO_LIB_VIAG_REST.json
- tre/rotas/WTA-BUSCAR_MSG_RETORNO_REPROG_REST.json
- tre/variaveis/TRE-ENVIAR_MSG_RETORNO_CANCEL -{{CLIENT_JSON}}.json
- tre/variaveis/TRE-ENVIAR_MSG_RETORNO_LIB_VIAG -{{CLIENT_JSON}}.json
- tre/variaveis/TRE-ENVIAR_MSG_RETORNO_REPROG -{{CLIENT_JSON}}.json
https://jiraproducao.totvs.com.br/browse/DDESTOQUE-21152
> Adapter de retornar mensagens ao TRE
